document.write('	<ul>	');
document.write('	    <li>	');
document.write('	        <h2>教育经历</h2>	');
document.write('	        <ul>	');
document.write('	            <li><a href="#">小学</a></li>	');
document.write('	            <li><a href="#">高中</a></li>	');
document.write('	            <li><a href="#">大学</a></li>	');
document.write('	            <li><a href="#">xxxxxx</a></li>	');
document.write('		');
document.write('	        </ul>	');
document.write('	    </li>	');
document.write('	    <li>	');
document.write('	        <h2>工作经历</h2>	');
document.write('	        <ul>	');
document.write('	            <li><a href="#">xxxx</a></li>	');
document.write('	            <li><a href="#">xxxx</a></li>	');
document.write('	            <li><a href="#">xxxx</a></li>	');
document.write('	            <li><a href="#">其他</a></li>	');
document.write('	        </ul>	');
document.write('	    </li>	');
document.write('	    <li>	');
document.write('	        <h2>实习经历</h2>	');
document.write('	        <ul>	');
document.write('	            <li><a href="#">xxxx</a></li>	');
document.write('	            <li><a href="#">xxxx</a></li>	');
document.write('	            <li><a href="#">xxxx</a></li>	');
document.write('	            <li><a href="#">xxxx</a></li>	');
document.write('	        </ul>	');
document.write('	    </li>	');
document.write('	    <li>	');
document.write('	        <h2>xx经历</h2>	');
document.write('	        <ul>	');
document.write('	            <li><a href="#">xxxx</a></li>	');
document.write('	            <li><a href="#">xxxx</a></li>	');
document.write('	            <li><a href="#">xxxx</a></li>	');
document.write('	            <li><a href="#">xxxx</a></li>	');
document.write('	        </ul>	');
document.write('	    </li>	');
document.write('	</ul>	');
